version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c " python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    env_file: .env
    depends_on:
      - db

    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:

